name: Run Parser

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать репозиторий
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Установить зависимости
        run: |
          pip install telethon

      - name: Запуск парсера
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          python parser.py
        run: |
          python parser.py
